@host = http://localhost:3333

POST {{host}}/person

{
	"name": "John",
	"age": 20
}

###
POST {{host}}/person

{
	"name": "Doe",
	"age": 30,
	"active": false
}

###
GET {{host}}/person

###
GET {{host}}/person/78e83872-7c0c-4a3b-ab11-3b6f3a19cadf

###
PATCH {{host}}/person/78e83872-7c0c-4a3b-ab11-3b6f3a19cadf

{
	"age": 40
}

###
DELETE {{host}}/person/1885f090-e082-4587-91b0-6a475c8e569a

